export const ITEMS_LIST_REQUEST = 'ITEMS_LIST_REQUEST';
export const ITEMS_LIST_SUCCESS = 'ITEMS_LIST_SUCCESS';
export const ITEMS_LIST_FAILS = 'ITEMS_LIST_FAILS';

export const ITEM_BY_ID_REQUEST = 'ITEM_BY_ID_REQUEST';
export const ITEM_BY_ID_SUCCESS = 'ITEM_BY_ID_SUCCESS';
export const ITEM_BY_ID_FAILS = 'ITEM_BY_ID_FAILS';
